=== phillipcheng/ereminder/Reminder/modules/shopping/target/classes/Task_2_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Tasks" type="TasksType"/>
	<xs:simpleType name="VarType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="xpath"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="page"/>
			<xs:enumeration value="list"/>
			<xs:enumeration value="pagelist"/>
			<xs:enumeration value="regexp"/>
			<xs:enumeration value="expression"/>
			<xs:enumeration value="externalList"/>
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="file"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="!="/>
			<xs:enumeration value="="/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ScopeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="const"/>
			<xs:enumeration value="param"/>
			<xs:enumeration value="attribute"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DirectionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOTH"/>
			<xs:enumeration value="IN"/>
			<xs:enumeration value="OUT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SplitTaskByType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="page"/>
			<xs:enumeration value="item"/>
			<xs:enumeration value="nothing"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ParamType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="VarType" use="optional" default="string"/>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>design time the default value, runtime will be assigned by taskInvoker</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ParamValueType">
		<xs:attribute name="paramName" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="type" type="VarType" use="optional" default="string"/>
		<xs:attribute name="scope" type="ScopeType"/>
	</xs:complexType>
	<xs:complexType name="ValueType">
		<xs:sequence>
			<xs:element name="strPreprocess" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="trimPre" type="xs:string"/>
					<xs:attribute name="trimPost" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="sampleUrl" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>multiple sample provided for toType is Page or Pagelist</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="pageVerify" type="PageVerifyType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>string to verify if page or pagelist type, for pagelist, this is also a list, 1-1 mapping.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fromScope" type="ScopeType"/>
		<xs:attribute name="fromType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>the value's input type, default to xpath</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="toType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>the type of the interpret result</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toEntryType" type="VarType" use="optional" default="string">
			<xs:annotation>
				<xs:documentation>the type of the entry in the list if toType is list type</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toDirectory">
			<xs:annotation>
				<xs:documentation>only for toEntryType is File, expression</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="basePage" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>based on which page, to eval this xpath</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enableJS" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>used with toType=page, if null, reusing previous wc setting</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="format" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>used with toType=date</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BrowseTaskType">
		<xs:sequence>
			<xs:element name="sampleUrl" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>multiple sample url for start url</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="param" type="ParamType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="userAttribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="idUrlMapping" type="RegExpType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>for bdt: 1. this is uni-directional, from url to id, 2. if not having this, id will be assigned in user attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="idUrlMappingFirstPage" type="RegExpType" minOccurs="0"/>
			<xs:element name="itemName" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="taskName" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if not specified, then this task can't be invoked explicitly</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isStart" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>true, started when engine starts, does not need an invoke</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="rerunInterim" type="xs:int" use="optional">
			<xs:annotation>
				<xs:documentation>if missing, means run only, else specify number of seconds before rerun</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enableJS" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="startUrl" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if isStart is true, then this is needed.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="skipJS" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="BrowseCatType">
		<xs:sequence>
			<xs:element name="baseBrowseTask" type="BrowseTaskType"/>
			<xs:element name="subItemList" type="SubListType"/>
			<xs:element name="totalPageNum" type="ValueType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>means how many pages of childitems we have, each page will be split in one task. 
if not set, but itemPerPage and totalItemNum set, this can be calculated.
if also not set, then 1 task browsing all items will be generated.
</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="itemPerPage" type="ValueType" minOccurs="0"/>
			<xs:element name="totalItemNum" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="isLeaf" type="xs:boolean" use="required"/>
		<xs:attribute name="splitTaskType" type="SplitTaskByType" use="optional" default="page"/>
	</xs:complexType>
	<xs:complexType name="BrowseDetailType">
		<xs:sequence>
			<xs:element name="baseBrowseTask" type="BrowseTaskType"/>
			<xs:element name="firstPageClickStream" type="ClickStreamType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>the click stream to the 1st page of the book</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="totalPage" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="nextPage" type="xs:string"/>
		<xs:attribute name="lastPageCondition" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>boolean expression</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="monitorPrice" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="SubListType">
		<xs:sequence>
			<xs:element name="itemList" type="ValueType">
				<xs:annotation>
					<xs:documentation>xpath to list of item, usually of type html element , but can be page or further click stream (TBD), then itemFullUrl is the abs xpath on the last page</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="taskInvokes" type="TaskInvokeType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>if not using item full url, then invoking prd Task by passing this param mapping</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="userAttribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="lastPageCondition" type="BinaryBoolOp" minOccurs="0"/>
			<xs:element name="name" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="itemFullUrl" type="xs:string" use="optional"/>
		<xs:attribute name="nextPage" type="xs:string" use="optional"/>
		<xs:attribute name="isLeaf" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="lastItem" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:element name="value" type="ValueType"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="nameType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>for input/set, the nameType defaults to XPATH, for get the nameType defaults to string</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="RegExpType">
		<xs:sequence>
			<xs:element name="Token" type="TokenType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BinaryBoolOp">
		<xs:attribute name="lhs" type="xs:string"/>
		<xs:attribute name="rhs" type="xs:string"/>
		<xs:attribute name="operator" type="OpType"/>
	</xs:complexType>
	<xs:complexType name="TokenType">
		<xs:annotation>
			<xs:documentation>for Id-Url mapping</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="type" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>this is fromType</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toType" type="VarType" use="optional" default="string"/>
		<xs:attribute name="dir" type="DirectionType" use="optional" default="BOTH">
			<xs:annotation>
				<xs:documentation>default both, IN means to url, OUT means from url</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ClickStreamType">
		<xs:annotation>
			<xs:documentation>For each click/link, first do some input assignment, then click the xpath typed nextpage and return a page.		</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="ClickType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>usually toType of nextpage is page, and name will be used in later expression
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="finishCondition" type="BinaryBoolOp" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						if specified, the last link will be clicked till
						finish condition, if true reach the first page
						of the book
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TasksType">
		<xs:sequence>
			<xs:element name="skipUrl" minOccurs="0" maxOccurs="unbounded">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CatTask" type="BrowseCatType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="PrdTask" type="BrowseDetailType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="invokeTask" type="TaskInvokeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="storeId" type="xs:string" use="required"/>
		<xs:attribute name="rootVolume" type="xs:string" use="required"/>
		<xs:attribute name="maxThread" type="xs:int" use="optional" default="0">
			<xs:annotation>
				<xs:documentation>max # threads can be used to crawl this site, default 0 for unlimited</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="productType" use="optional" default="book">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="book"/>
					<xs:enumeration value="default"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TaskInvokeType">
		<xs:sequence>
			<xs:element name="param" type="ParamValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="myTaskName"/>
		<xs:attribute name="toCallTaskName" type="xs:string">
			<xs:annotation>
				<xs:documentation>if not specified, default to the first product task</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ClickType">
		<xs:sequence>
			<xs:element name="input" type="AttributeType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>parameters to input</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="nextpage" type="AttributeType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PageVerifyType">
		<xs:attribute name="xpath" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if this is missing, then root</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="expectedContent" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if this is missing, then xpath should exist</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/nasdaq-holding-summary.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="nasdaq-holding-summary" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="false" dsm="nothing" taskName="nasdaq-holding-summary" mbMemoryNeeded="1024">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<startUrl value="'http://www.nasdaq.com/symbol/' + stockid.toLowerCase() + '/ownership-summary'" fromType="expression"/>
			<userAttribute name="id">
				<value value="stockid + '_' + endDate" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="1,2" toType="list" toEntryType="int"/>
			</userAttribute>
			<userAttribute name="ColCsvName">
				<value value="InstitutionalSummary,InsiderSummary" toType="list" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="data1">
				<value value="//div[@id='outstanding']/following-sibling::div[1]/div[1]/table/tbody/tr/td" toType="list" toEntryType="string" optional="true"/>
			</userAttribute>
			<userAttribute name="data2">
				<value value="//div[@id='holders-stacked']/following-sibling::div[1]/div[1]/table/tbody/tr/td" toType="list" toEntryType="string" optional="true"/>
			</userAttribute>
			<csvtransform outputType="byJobMulti" transformClass="org.cld.etl.csv.MultiColTablesAsCSV">
				<outputDir value="'raw/' + marketId + '_' + startDate + '_' + endDate + '/nasdaq-holding-summary/'" fromType="expression"/>
			</csvtransform>
		</baseBrowseTask>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/book/src/main/resources/childrenslibrary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" storeId="childrenslibrary" rootVolume="999999" productType="book">
	<CatTask isLeaf="true">
		<baseBrowseTask taskName="cat-0" isStart="true" enableJS="false">
			<startUrl value="http://www.childrenslibrary.org/icdl/TextSearch?page=1"/>
			<idUrlMapping>
				<Token name="prefix" value="http://www." type="string"/>
				<Token name="id" value="childrenslibrary" type="string"/>
				<Token name="mid" value=".org/icdl/TextSearch?page=" type="string"/>
				<Token name="pageNum" value="[0-9]+" type="regexp"/>
			</idUrlMapping>
			<itemName value="childrenslibrary"/>
		</baseBrowseTask>
		<subItemList nextPage="//img[@id=&apos;reader_arrow_right_bottom&apos;]">
			<itemList value="//body/table[1]/tbody/tr/td"/>
			<itemFullUrl value="a[1]" toType="url"/>
		</subItemList>
		<itemPerPage value="//select[@name=&apos;pgct&apos;]/option[@selected]"/>
		<totalItemNum value="//body/div[3]/div[2]/span[1]">
			<strPreprocess trimPost="books"/>
		</totalItemNum>
	</CatTask>
	<PrdTask>
		<baseBrowseTask taskName="prd" enableJS="false">
			<userAttribute name="bookpageurls">
				<value value="//a[@id='next_cover']/img" fromType="xpath" toType="externalList"/>
			</userAttribute>
			<idUrlMapping>
				<Token name="prefix" value="http://www.childrenslibrary.org/icdl/BookPreview?bookid=" type="string"/>
				<Token name="id" value="[_a-zA-Z0-9]+" type="regexp"/>
				<Token name="suffix" value="&amp;.*" type="regexp"/>
			</idUrlMapping>
			<itemName value="//body/table[1]/tbody/tr/td/table[1]/tbody/tr/td/span[1]"/>
		</baseBrowseTask>
		<firstPageClickStream>
			<link>
				<nextpage>
					<successNextPage name="indexPage">
						<value value="//a[@id=&apos;readbook_link&apos;]" toType="page"/>
					</successNextPage>
				</nextpage>
			</link>
			<link>
				<nextpage>
					<successNextPage name="firstPage">
						<value value="//div[@id=&apos;bookpages&apos;]/a[1]" toType="page" basePage="indexPage"/>
					</successNextPage>
				</nextpage>
			</link>
		</firstPageClickStream>
		<totalPage value="count(//div[@id=&apos;bookpages&apos;]/a|//div[@id=&apos;bookpages&apos;]/span/a)" toType="int" basePage="indexPage"/>
		<nextPage value="//a[@id=&apos;next_bottom&apos;]"/>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/nasdaq-fr-quarter-IncomeStatement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="nasdaq-fr-quarter-IncomeStatement" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" dsm="nothing" taskName="nasdaq-fr-quarter-IncomeStatement" mbMemoryNeeded="1024">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<param name="quarter" type="int" value="0"/>
			<param name="year" type="int" value="0"/>
			<startUrl value="'http://www.nasdaq.com/symbol/' + stockid.toLowerCase() + '/financials?query=income-statement&amp;data=quarterly'" fromType="expression"/>
			<userAttribute name="id">
				<value value="stockid + '_' + endDate" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="4" toType="int"/>
			</userAttribute>
			<userAttribute name="DataType">
				<value value="Text,Date" toType="list" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="data">
				<value value="//div[@id='financials-iframe-wrap']/div[1]/table[1]/thead/tr/th[position()>2]|//div[@id='financials-iframe-wrap']/div[1]/table[1]/tbody/tr/td[position()>1]" toType="list" toEntryType="string" optional="true"/>
			</userAttribute>
			<csvtransform outputType="byId" reverse="true" transformClass="org.cld.etl.csv.SpreadColTableAsCSV">
			</csvtransform>
			<filter>function getDate(q) {
    if (q=='1') return '-03-31'
    if (q=='2') return '-06-30'
    if (q=='3') return '-09-30'
    if (q=='4') return '-12-31'
}
year==0 || quarter==0 || arr[1]&gt;=(year+getDate(quarter))</filter>
		</baseBrowseTask>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/sina-stock-fr-quarter-CashFlow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="sina-stock-fr-quarter-CashFlow" productType="default">
	<PrdTask>
		<baseBrowseTask enableJS="true" taskName="cashflow">
			<param name="stockid"/>
			<param name="year"/>
			<param name="quarter"/>
			<param name="startDate" type="string"/>
			<param name="endDate" type="string"/>
			<startUrl value="http://money.finance.sina.com.cn/corp/go.php/vFD_CashFlow/stockid/[stockid]/ctrl/[year]/displaytype/4.phtml"/>
			<userAttribute name="id">
				<value value="stockid + '_' + year + '_' + quarter" toType="string" fromType="expression"/>
			</userAttribute>
			<userAttribute name="quarterAvail">
				<value value="count(//table[@id='ProfitStatementNewTable0']/tbody/tr[1]/td)" toType="int" optional="true"/>
			</userAttribute>
			<userAttribute name="data">
				<value value="quarterAvail>quarter? &quot;//table[@id='ProfitStatementNewTable0']/tbody/tr[count(td)>1]/td[&quot; + (quarterAvail + 1 - quarter) + &quot;]&quot; : null" toType="list" fromType="expression" optional="true"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="1" toType="int"/>
			</userAttribute>
			<userAttribute name="HasHeader">
				<value value="false" toType="boolean"/>
			</userAttribute>
			<pageVerify operator="!=">
				<lhs value="//table[@id='ProfitStatementNewTable0']/tbody/tr/td">
				</lhs>
				<rhs value="null">
				</rhs>
			</pageVerify>
			<csvtransform transformClass="org.cld.etl.csv.SpreadColTableAsCSV" outputType="byJobSingle">
				<outputDir value="raw/[startDate]_[endDate]/sina-stock-fr-quarter-CashFlow/[year]_[quarter]"/>
			</csvtransform>
		</baseBrowseTask>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/shopping/target/test-classes/vyming.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\reminder\maven.1411262641248\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" storeId="vyming" rootVolume="999996" maxThread="1">
	<CatTask isLeaf="false">
		<baseBrowseTask enableJS="false" startUrl="http://bbs.vyming.com/novel-list-0-0-0-0-0-0-0-1.html">
			<idUrlMapping>
				<Token name="prefix" value="http://bbs."/>
				<Token name="id" value="vyming"/>
				<Token name="suffix" value=".com/novel-list-0-0-0-0-0-0-0-1.html"/>
			</idUrlMapping>
		</baseBrowseTask>
		<subItemList isLeaf="true">
			<itemList value="//div[@id=&apos;nv&apos;]/ul/li/a"/>
			<name value="./text()"/>
		</subItemList>
		<totalPageNum value="1"/>
	</CatTask>
	<CatTask isLeaf="true">
		<baseBrowseTask enableJS="false" startUrl="http://bbs.vyming.com/novel-list-1-0-0-0-0-0-0-1.html">
			<idUrlMapping>
				<Token name="prefix" value="http://bbs.vyming.com/novel-list-" type="string"/>
				<Token name="id" value="[1-9]+" type="regexp"/>
				<Token name="mid" value="-0-0-0-0-0-0-" type="string"/>
				<Token name="pageNum" value="[0-9]+" type="regexp"/>
				<Token name="suffix" value=".html" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
		<subItemList itemFullUrl="./div[1]/a[1]" isLeaf="true" lastItem="./div[1]/a[last()]/text()">
			<itemList value="//*[@id=&quot;pdmodule&quot;]/div[4]/div/div[2]/div"/>
			<userAttribute name="author">
				<value value="./div[1]/a[2]/following::text()[1]">
					<strPreprocess trimPost="/&#33879;"/>
				</value>
			</userAttribute>
			<userAttribute name="utime">
				<value value="./div[1]/a[2]/following::text()[2]" toType="date" format="yyyy-MM-dd hh:mm">
					<strPreprocess trimPost="&#26356;&#26032;&#33267;&#65306;"/>
				</value>
			</userAttribute>
			<name value="./div[1]/a[1]/@title"/>
		</subItemList>
		<totalPageNum value="//input[@id=&apos;pageindex1&apos;]/@value"/>
	</CatTask>
	<PrdTask imagePath="//*[@id=&quot;showcontent&quot;]">
		<baseBrowseTask enableJS="false" startUrl="http://bbs.vyming.com/novel-view-18301.html">
			<idUrlMapping>
				<Token name="prefix" value="http://bbs.vyming.com/novel-view-" type="string"/>
				<Token name="id" value="[0-9]+" type="regexp"/>
				<Token name="suffix" value=".html" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
		<firstPageClickStream>
			<link>
				<nextpage name="indexPage">
					<value value="//*[@id=&quot;info&quot;]/div[5]/a[2]">
						<sampleUrl>http://bbs.vyming.com/novel-chapter-18301.html</sampleUrl>
						<sampleUrl>http://bbs.vyming.com/novel-read-18301-3912991.html</sampleUrl>
					</value>
				</nextpage>
			</link>
		</firstPageClickStream>
		<directPages value="//div[@class=&apos;contentlist&apos;]/ul/a" toType="list" basePage="indexPage"/>
	</PrdTask>
</Tasks>
