=== phillipcheng/ereminder/Reminder/modules/shopping/target/classes/Task_2_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Tasks" type="TasksType"/>
	<xs:simpleType name="VarType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="xpath"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="page"/>
			<xs:enumeration value="list"/>
			<xs:enumeration value="pagelist"/>
			<xs:enumeration value="regexp"/>
			<xs:enumeration value="expression"/>
			<xs:enumeration value="externalList"/>
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="file"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="!="/>
			<xs:enumeration value="="/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ScopeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="const"/>
			<xs:enumeration value="param"/>
			<xs:enumeration value="attribute"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DirectionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOTH"/>
			<xs:enumeration value="IN"/>
			<xs:enumeration value="OUT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SplitTaskByType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="page"/>
			<xs:enumeration value="item"/>
			<xs:enumeration value="nothing"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ParamType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="VarType" use="optional" default="string"/>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>design time the default value, runtime will be assigned by taskInvoker</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ParamValueType">
		<xs:attribute name="paramName" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="type" type="VarType" use="optional" default="string"/>
		<xs:attribute name="scope" type="ScopeType"/>
	</xs:complexType>
	<xs:complexType name="ValueType">
		<xs:sequence>
			<xs:element name="strPreprocess" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="trimPre" type="xs:string"/>
					<xs:attribute name="trimPost" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="sampleUrl" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>multiple sample provided for toType is Page or Pagelist</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="pageVerify" type="PageVerifyType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>string to verify if page or pagelist type, for pagelist, this is also a list, 1-1 mapping.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fromScope" type="ScopeType"/>
		<xs:attribute name="fromType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>the value's input type, default to xpath</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="toType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>the type of the interpret result</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toEntryType" type="VarType" use="optional" default="string">
			<xs:annotation>
				<xs:documentation>the type of the entry in the list if toType is list type</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toDirectory">
			<xs:annotation>
				<xs:documentation>only for toEntryType is File, expression</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="basePage" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>based on which page, to eval this xpath</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enableJS" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>used with toType=page, if null, reusing previous wc setting</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="format" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>used with toType=date</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BrowseTaskType">
		<xs:sequence>
			<xs:element name="sampleUrl" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>multiple sample url for start url</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="param" type="ParamType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="userAttribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="idUrlMapping" type="RegExpType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>for bdt: 1. this is uni-directional, from url to id, 2. if not having this, id will be assigned in user attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="idUrlMappingFirstPage" type="RegExpType" minOccurs="0"/>
			<xs:element name="itemName" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="taskName" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if not specified, then this task can't be invoked explicitly</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isStart" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>true, started when engine starts, does not need an invoke</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="rerunInterim" type="xs:int" use="optional">
			<xs:annotation>
				<xs:documentation>if missing, means run only, else specify number of seconds before rerun</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enableJS" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="startUrl" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if isStart is true, then this is needed.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="skipJS" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="BrowseCatType">
		<xs:sequence>
			<xs:element name="baseBrowseTask" type="BrowseTaskType"/>
			<xs:element name="subItemList" type="SubListType"/>
			<xs:element name="totalPageNum" type="ValueType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>means how many pages of childitems we have, each page will be split in one task. 
if not set, but itemPerPage and totalItemNum set, this can be calculated.
if also not set, then 1 task browsing all items will be generated.
</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="itemPerPage" type="ValueType" minOccurs="0"/>
			<xs:element name="totalItemNum" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="isLeaf" type="xs:boolean" use="required"/>
		<xs:attribute name="splitTaskType" type="SplitTaskByType" use="optional" default="page"/>
	</xs:complexType>
	<xs:complexType name="BrowseDetailType">
		<xs:sequence>
			<xs:element name="baseBrowseTask" type="BrowseTaskType"/>
			<xs:element name="firstPageClickStream" type="ClickStreamType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>the click stream to the 1st page of the book</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="totalPage" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="nextPage" type="xs:string"/>
		<xs:attribute name="lastPageCondition" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>boolean expression</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="monitorPrice" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="SubListType">
		<xs:sequence>
			<xs:element name="itemList" type="ValueType">
				<xs:annotation>
					<xs:documentation>xpath to list of item, usually of type html element , but can be page or further click stream (TBD), then itemFullUrl is the abs xpath on the last page</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="taskInvokes" type="TaskInvokeType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>if not using item full url, then invoking prd Task by passing this param mapping</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="userAttribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="lastPageCondition" type="BinaryBoolOp" minOccurs="0"/>
			<xs:element name="name" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="itemFullUrl" type="xs:string" use="optional"/>
		<xs:attribute name="nextPage" type="xs:string" use="optional"/>
		<xs:attribute name="isLeaf" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="lastItem" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:element name="value" type="ValueType"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="nameType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>for input/set, the nameType defaults to XPATH, for get the nameType defaults to string</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="RegExpType">
		<xs:sequence>
			<xs:element name="Token" type="TokenType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BinaryBoolOp">
		<xs:attribute name="lhs" type="xs:string"/>
		<xs:attribute name="rhs" type="xs:string"/>
		<xs:attribute name="operator" type="OpType"/>
	</xs:complexType>
	<xs:complexType name="TokenType">
		<xs:annotation>
			<xs:documentation>for Id-Url mapping</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="type" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>this is fromType</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toType" type="VarType" use="optional" default="string"/>
		<xs:attribute name="dir" type="DirectionType" use="optional" default="BOTH">
			<xs:annotation>
				<xs:documentation>default both, IN means to url, OUT means from url</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ClickStreamType">
		<xs:annotation>
			<xs:documentation>For each click/link, first do some input assignment, then click the xpath typed nextpage and return a page.		</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="ClickType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>usually toType of nextpage is page, and name will be used in later expression
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="finishCondition" type="BinaryBoolOp" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						if specified, the last link will be clicked till
						finish condition, if true reach the first page
						of the book
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TasksType">
		<xs:sequence>
			<xs:element name="skipUrl" minOccurs="0" maxOccurs="unbounded">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CatTask" type="BrowseCatType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="PrdTask" type="BrowseDetailType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="invokeTask" type="TaskInvokeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="storeId" type="xs:string" use="required"/>
		<xs:attribute name="rootVolume" type="xs:string" use="required"/>
		<xs:attribute name="maxThread" type="xs:int" use="optional" default="0">
			<xs:annotation>
				<xs:documentation>max # threads can be used to crawl this site, default 0 for unlimited</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="productType" use="optional" default="book">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="book"/>
					<xs:enumeration value="default"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TaskInvokeType">
		<xs:sequence>
			<xs:element name="param" type="ParamValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="myTaskName"/>
		<xs:attribute name="toCallTaskName" type="xs:string">
			<xs:annotation>
				<xs:documentation>if not specified, default to the first product task</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ClickType">
		<xs:sequence>
			<xs:element name="input" type="AttributeType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>parameters to input</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="nextpage" type="AttributeType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PageVerifyType">
		<xs:attribute name="xpath" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if this is missing, then root</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="expectedContent" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if this is missing, then xpath should exist</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/nasdaq-quote-premarket.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="nasdaq-quote-premarket" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" dsm="nothing" taskName="quote-premarket-0" mbMemoryNeeded="1024">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<startUrl value="http://www.nasdaq.com/zh/symbol/[stockid]/premarket"/>
			<userAttribute name="dateDisplay">
				<value value="//div[@id='quotes_content_left__panelGoodSymbol']/div[2]/small/text()" toType="date" format="yyyy/MM/dd">
					<strPreprocess trimPost="上一次收盘"/>
				</value>
			</userAttribute>
			<userAttribute name="id">
				<value value="stockid + '_' + (new Date(dateDisplay)).getFullYear() + '-' + ((new Date(dateDisplay)).getMonth()+1) + '-' + (new Date(dateDisplay)).getDate()" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="3" toType="list" toEntryType="int"/>
			</userAttribute>
			<userAttribute name="data1">
				<value value="//table[@id='AfterHoursPagingContents_Table']/tbody/tr/td" toType="list" toEntryType="string"/>
			</userAttribute>
			<csvtransform outputType="byId" reverse="true" transformClass="org.cld.etl.csv.MultiRowTablesAsCSV">
				<outputDir value="raw/[marketId]/nasdaq-quote-premarket/[endDate]"/>
			</csvtransform>
			<nextTask>
				<condition>data1 != null &amp;&amp; data1.toArray().length>140</condition>
				<invokeTask toCallTaskName="quote-premarket-real"/>
			</nextTask>
		</baseBrowseTask>
	</PrdTask>
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" dsm="hdfs" taskName="quote-premarket-real" mbMemoryNeeded="1024" isStart="false">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<param name="timeperiod" type="list" value="1,2,3,4,5,6,7,8,9,10,11"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<startUrl value="'http://www.nasdaq.com/zh/symbol/' + stockid.toLowerCase() + '/premarket?time=' + timeperiod" fromType="expression"/>
			<userAttribute name="dateDisplay">
				<value value="//div[@id='quotes_content_left__panelGoodSymbol']/div[2]/small/text()" toType="date" format="yyyy/MM/dd">
					<strPreprocess trimPost="上一次收盘"/>
				</value>
			</userAttribute>
			<userAttribute name="id">
				<value value="stockid + '_' + (new Date(dateDisplay)).getFullYear() + '-' + ((new Date(dateDisplay)).getMonth()+1) + '-' + (new Date(dateDisplay)).getDate()" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="3" toType="list" toEntryType="int"/>
			</userAttribute>
			<userAttribute name="data1">
				<value value="//table[@id='AfterHoursPagingContents_Table']/tbody/tr/td" toType="externalList" toEntryType="string"/>
			</userAttribute>
			<csvtransform outputType="byId" reverse="true" transformClass="org.cld.etl.csv.MultiRowTablesAsCSV">
				<outputDir value="raw/[marketId]/nasdaq-quote-premarket/[endDate]"/>
			</csvtransform>
		</baseBrowseTask>
		<nextPage value="//div[@id='pagerContainer']/div[1]/ul[1]/li[last()-1]/a" optional="true"/>
		<lastPageCondition>nextPage == null</lastPageCondition>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/sina-stock-fr-history.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="sina-stock-fr-history" productType="default">
	<!-- all financial reports -->
	<PrdTask>
		<baseBrowseTask enableJS="true" taskName="all-balancesheet">
			<param name="stockid"/>
			<startUrl value="http://money.finance.sina.com.cn/corp/go.php/vDOWN_BalanceSheet/displaytype/4/stockid/[stockid]/ctrl/all.phtml"/>
			<cachePage value="BalanceSheet/[stockid]"/>
			<idUrlMapping>
				<Token value="http://money.finance.sina.com.cn/corp/go.php/vDOWN_BalanceSheet/displaytype/4/stockid/" name="prefix" type="string"/>
				<Token value="[0-9]+" name="id" type="regexp"/>
				<Token value="/ctrl/all.phtml" name="suffix" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
	</PrdTask>
	<PrdTask>
		<baseBrowseTask enableJS="true" taskName="all-profitstatement">
			<param name="stockid"/>
			<startUrl value="http://money.finance.sina.com.cn/corp/go.php/vDOWN_ProfitStatement/displaytype/4/stockid/[stockid]/ctrl/all.phtml"/>
			<cachePage value="ProfitStatement/[stockid]"/>
			<idUrlMapping>
				<Token value="http://money.finance.sina.com.cn/corp/go.php/vDOWN_ProfitStatement/displaytype/4/stockid/" name="prefix" type="string"/>
				<Token value="[0-9]+" name="id" type="regexp"/>
				<Token value="/ctrl/all.phtml" name="suffix" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
	</PrdTask>
	<PrdTask>
		<baseBrowseTask enableJS="true" taskName="all-cashflow">
			<param name="stockid"/>
			<startUrl value="http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/[stockid]/ctrl/all.phtml"/>
			<cachePage value="CashFlow/[stockid]"/>
			<idUrlMapping>
				<Token value="http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/" name="prefix" type="string"/>
				<Token value="[0-9]+" name="id" type="regexp"/>
				<Token value="/ctrl/all.phtml" name="suffix" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/nasdaq-quote-oneminute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="nasdaq-quote-oneminute" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" dsm="hdfs" taskName="quote-onemiute" mbMemoryNeeded="512">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<startUrl value="http://www.nasdaq.com/symbol/[stockid]/interactive-chart"/>
			<userAttribute name="id">
				<value value="stockid" toType="string" fromType="expression"/>
			</userAttribute>
			<userAttribute name="file">
				<value frameId="4" value="//div[@id='gridContainer']/div[1]/span[1]" toDirectory="raw/[marketId]/[startDate]_[endDate]/quote-oneminute/[stockid]" toType="file"/>
			</userAttribute>
		</baseBrowseTask>
		<firstPageClickStream>
			<link>
				<nextpage>
					<successNextPage name="setExtend">
						<value frameId="4" value="//ul[@id='chart-display']/li[@stxtoggle='toggleExt()']"/>
					</successNextPage>
				</nextpage>
			</link>
			<link>
				<nextpage>
					<successNextPage name="setGranular">
						<value frameId="4" value="//ul[@id='periodicity']/li[text()='1 D']"/>
					</successNextPage>
				</nextpage>
			</link>
			<link>
				<nextpage>
					<successNextPage name="setRange">
						<value frameId="4" value="//div[@id='stxViewRange']/ul[1]/li[@id='range1m']"/>
					</successNextPage>
				</nextpage>
			</link>
			<link>
				<nextpage>
					<successNextPage name="loadTable">
						<value frameId="4" value="//div[@id='dataTableBtn']">
							<pageVerify operator="!=">
								<lhs value="//div[@id='gridContainer']/div[1]/div[2]"/>
								<rhs value="null"/>
							</pageVerify>
						</value>
					</successNextPage>
				</nextpage>
			</link>
		</firstPageClickStream>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/sina-stock-market-dzjy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" 
rootVolume="999990" 
storeId="sina-stock-market-dzjy" 
productType="default">
	<!-- HS_A market allows rzrq since 2012/11/12 -->
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" 
		taskName="market-dzjy" 
		dsm="hdfs">
			<param name="date"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<startUrl value="http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/dzjy/index.phtml?bdate=[date]&amp;edate=[date]&amp;num=20"/>
			<userAttribute name="id">
				<value value="date" fromScope="param"/>
			</userAttribute>
			<userAttribute name="stockid"> <!-- needed for the csv etl should be renamed into kid -->
				<value value="date" fromScope="param"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="9" toType="list" toEntryType="int"/>
			</userAttribute>
			<userAttribute name="data1">
				<value value="//table[@id='dataTable']/tbody/tr[count(td)>1]/td" toType="externalList" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="RowCsvName">
				<value value="dzjy" toType="list" />
			</userAttribute>
			<csvtransform transformClass="org.cld.etl.csv.MultiRowTablesAsCSV" multipleOutput="true"/>
		</baseBrowseTask>
		<nextPage optional="true" value="//div[@class='pages']/a[last()]">
		</nextPage>
		<lastPageCondition operator="!=">
			<lhs value="//div[@class='pages']/a[last()]/@class"></lhs>
			<rhs value="page"></rhs>
		</lastPageCondition>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/cld-datacrawl/src/test/resources/hkse-stock-basic.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\reminder\maven.1411262641248\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="hkse-stock-basic" productType="default">
	<CatTask isLeaf="true" splitTaskType="item">
		<baseBrowseTask enableJS="false" startUrl="http://www.hkex.com.hk/chi/market/sec_tradinfo/stockcode/eisdeqty_c.htm">
			<idUrlMapping>
				<Token value="http://www.hkex.com.hk/chi/market/sec_tradinfo/stockcode/eisdeqty_c.htm" name="id" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
		<subItemList>
			<itemList value="//table[@class='table_grey_border']/tbody/tr[position()>1]"/>
			<prdTaskParamMapping paramName="symbal" value="code" scope="attribute"/>
			<userAttribute name="code">
				<value value="td[1]/text()"/>
			</userAttribute>
		</subItemList>
		<totalPageNum value="1"/>
	</CatTask>
	<PrdTask nextPage="//input[@id='ctl00_gvMain_ctl01_btnNext']">
		<baseBrowseTask startUrl="http://www.hkexnews.hk/listedco/listconews/advancedsearch/search_active_main_c.aspx" enableJS="true" taskName="hksePrd">
			<param name="symbal" type="string"/>
			<userAttribute name="id">
				<value value="symbal" fromScope="param"/>
			</userAttribute>
			<userAttribute name="files">
				<value value="//table[@id='ctl00_gvMain']/tbody/tr/td[4]/a" toType="externalList" toEntryType="file" toDirectory="id"/>
			</userAttribute>
		</baseBrowseTask>
		<firstPageClickStream>
			<link>
				<input name="//input[@id='ctl00_txt_stock_code']">
					<value value="symbal" fromScope="param"/>
				</input>
				<nextpage name="resultpage">
					<value value="//form[@id='aspnetForm']/table[last()]/tbody/tr[last()]/td[last()]/label/a[1]"/>
				</nextpage>
			</link>
		</firstPageClickStream>
	</PrdTask>
</Tasks>
