=== phillipcheng/ereminder/Reminder/modules/shopping/target/classes/Task_2_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Tasks" type="TasksType"/>
	<xs:simpleType name="VarType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="xpath"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="page"/>
			<xs:enumeration value="list"/>
			<xs:enumeration value="pagelist"/>
			<xs:enumeration value="regexp"/>
			<xs:enumeration value="expression"/>
			<xs:enumeration value="externalList"/>
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="file"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OpType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="!="/>
			<xs:enumeration value="="/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ScopeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="const"/>
			<xs:enumeration value="param"/>
			<xs:enumeration value="attribute"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DirectionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOTH"/>
			<xs:enumeration value="IN"/>
			<xs:enumeration value="OUT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SplitTaskByType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="page"/>
			<xs:enumeration value="item"/>
			<xs:enumeration value="nothing"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ParamType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="VarType" use="optional" default="string"/>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>design time the default value, runtime will be assigned by taskInvoker</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ParamValueType">
		<xs:attribute name="paramName" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="type" type="VarType" use="optional" default="string"/>
		<xs:attribute name="scope" type="ScopeType"/>
	</xs:complexType>
	<xs:complexType name="ValueType">
		<xs:sequence>
			<xs:element name="strPreprocess" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="trimPre" type="xs:string"/>
					<xs:attribute name="trimPost" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="sampleUrl" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>multiple sample provided for toType is Page or Pagelist</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="pageVerify" type="PageVerifyType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>string to verify if page or pagelist type, for pagelist, this is also a list, 1-1 mapping.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fromScope" type="ScopeType"/>
		<xs:attribute name="fromType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>the value's input type, default to xpath</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="toType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>the type of the interpret result</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toEntryType" type="VarType" use="optional" default="string">
			<xs:annotation>
				<xs:documentation>the type of the entry in the list if toType is list type</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toDirectory">
			<xs:annotation>
				<xs:documentation>only for toEntryType is File, expression</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="basePage" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>based on which page, to eval this xpath</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enableJS" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>used with toType=page, if null, reusing previous wc setting</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="format" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>used with toType=date</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BrowseTaskType">
		<xs:sequence>
			<xs:element name="sampleUrl" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>multiple sample url for start url</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="param" type="ParamType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="userAttribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="idUrlMapping" type="RegExpType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>for bdt: 1. this is uni-directional, from url to id, 2. if not having this, id will be assigned in user attribute</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="idUrlMappingFirstPage" type="RegExpType" minOccurs="0"/>
			<xs:element name="itemName" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="taskName" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if not specified, then this task can't be invoked explicitly</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isStart" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>true, started when engine starts, does not need an invoke</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="rerunInterim" type="xs:int" use="optional">
			<xs:annotation>
				<xs:documentation>if missing, means run only, else specify number of seconds before rerun</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enableJS" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="startUrl" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if isStart is true, then this is needed.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="skipJS" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="BrowseCatType">
		<xs:sequence>
			<xs:element name="baseBrowseTask" type="BrowseTaskType"/>
			<xs:element name="subItemList" type="SubListType"/>
			<xs:element name="totalPageNum" type="ValueType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>means how many pages of childitems we have, each page will be split in one task. 
if not set, but itemPerPage and totalItemNum set, this can be calculated.
if also not set, then 1 task browsing all items will be generated.
</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="itemPerPage" type="ValueType" minOccurs="0"/>
			<xs:element name="totalItemNum" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="isLeaf" type="xs:boolean" use="required"/>
		<xs:attribute name="splitTaskType" type="SplitTaskByType" use="optional" default="page"/>
	</xs:complexType>
	<xs:complexType name="BrowseDetailType">
		<xs:sequence>
			<xs:element name="baseBrowseTask" type="BrowseTaskType"/>
			<xs:element name="firstPageClickStream" type="ClickStreamType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>the click stream to the 1st page of the book</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="totalPage" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="nextPage" type="xs:string"/>
		<xs:attribute name="lastPageCondition" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>boolean expression</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="monitorPrice" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="SubListType">
		<xs:sequence>
			<xs:element name="itemList" type="ValueType">
				<xs:annotation>
					<xs:documentation>xpath to list of item, usually of type html element , but can be page or further click stream (TBD), then itemFullUrl is the abs xpath on the last page</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="taskInvokes" type="TaskInvokeType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>if not using item full url, then invoking prd Task by passing this param mapping</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="userAttribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="lastPageCondition" type="BinaryBoolOp" minOccurs="0"/>
			<xs:element name="name" type="ValueType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="itemFullUrl" type="xs:string" use="optional"/>
		<xs:attribute name="nextPage" type="xs:string" use="optional"/>
		<xs:attribute name="isLeaf" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="lastItem" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="AttributeType">
		<xs:sequence>
			<xs:element name="value" type="ValueType"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="nameType" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>for input/set, the nameType defaults to XPATH, for get the nameType defaults to string</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="RegExpType">
		<xs:sequence>
			<xs:element name="Token" type="TokenType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BinaryBoolOp">
		<xs:attribute name="lhs" type="xs:string"/>
		<xs:attribute name="rhs" type="xs:string"/>
		<xs:attribute name="operator" type="OpType"/>
	</xs:complexType>
	<xs:complexType name="TokenType">
		<xs:annotation>
			<xs:documentation>for Id-Url mapping</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="type" type="VarType" use="optional">
			<xs:annotation>
				<xs:documentation>this is fromType</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="toType" type="VarType" use="optional" default="string"/>
		<xs:attribute name="dir" type="DirectionType" use="optional" default="BOTH">
			<xs:annotation>
				<xs:documentation>default both, IN means to url, OUT means from url</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ClickStreamType">
		<xs:annotation>
			<xs:documentation>For each click/link, first do some input assignment, then click the xpath typed nextpage and return a page.		</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="ClickType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>usually toType of nextpage is page, and name will be used in later expression
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="finishCondition" type="BinaryBoolOp" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						if specified, the last link will be clicked till
						finish condition, if true reach the first page
						of the book
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TasksType">
		<xs:sequence>
			<xs:element name="skipUrl" minOccurs="0" maxOccurs="unbounded">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CatTask" type="BrowseCatType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="PrdTask" type="BrowseDetailType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="invokeTask" type="TaskInvokeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="storeId" type="xs:string" use="required"/>
		<xs:attribute name="rootVolume" type="xs:string" use="required"/>
		<xs:attribute name="maxThread" type="xs:int" use="optional" default="0">
			<xs:annotation>
				<xs:documentation>max # threads can be used to crawl this site, default 0 for unlimited</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="productType" use="optional" default="book">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="book"/>
					<xs:enumeration value="default"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TaskInvokeType">
		<xs:sequence>
			<xs:element name="param" type="ParamValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="myTaskName"/>
		<xs:attribute name="toCallTaskName" type="xs:string">
			<xs:annotation>
				<xs:documentation>if not specified, default to the first product task</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ClickType">
		<xs:sequence>
			<xs:element name="input" type="AttributeType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>parameters to input</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="nextpage" type="AttributeType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PageVerifyType">
		<xs:attribute name="xpath" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if this is missing, then root</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="expectedContent" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>if this is missing, then xpath should exist</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/shse-stock-ids.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="shse-stock-id" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" taskName="shA-trading-ids">
			<startUrl value="http://biz.sse.com.cn/sseportal/webapp/datapresent/SSEQueryStockInfoAct?reportName=BizCompStockInfoRpt"/>
			<userAttribute name="id">
				<value value="'shA-trading-ids_'+date" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ids">
				<value value="//table[@bgcolor='#337fb2']/tbody/tr[position()&gt;1]/td[1]/a/text()" toType="externalList"/>
			</userAttribute>
		</baseBrowseTask>
		<totalPage value="//td[@class='nextpage']/strong[2]/text()" toType="int"></totalPage>
		<nextPage value="//td[@class='nextpage']/a[last()]"/>
	</PrdTask>
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" taskName="shA-suspend-ids">
			<startUrl value="http://biz.sse.com.cn/sseportal/webapp/datapresent/SSEQueryStockInfoAct?keyword=&amp;reportName=BizCompStockInfoRpt&amp;PRODUCTID=&amp;PRODUCTJP=&amp;PRODUCTNAME=&amp;CURSOR=1&amp;tab_flg=4"/>
			<userAttribute name="id">
				<value value="'shA-suspend-ids_'+date" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ids">
				<value value="//table[@bgcolor='#337fb2']/tbody/tr[position()&gt;1]/td[1]/a/text()" toType="list"/>
			</userAttribute>
			<userAttribute name="suspendDate">
				<value value="//table[@bgcolor='#337fb2']/tbody/tr[position()&gt;1]/td[4]/text()" toType="list"/>
			</userAttribute>
		</baseBrowseTask>
		<totalPage value="1" toType="int"></totalPage>
	</PrdTask>
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="true" taskName="shA-delisted-ids">
			<startUrl value="http://biz.sse.com.cn/sseportal/webapp/datapresent/SSEQueryStockInfoAct?keyword=&amp;reportName=BizCompStockInfoRpt&amp;PRODUCTID=&amp;PRODUCTJP=&amp;PRODUCTNAME=&amp;CURSOR=1&amp;tab_flg=5"/>
			<userAttribute name="id">
				<value value="'shA-delisted-ids_'+date" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ids">
				<value value="//table[@bgcolor='#337fb2']/tbody/tr[position()&gt;1]/td[1]/a/text()" toType="list"/>
			</userAttribute>
			<userAttribute name="delistDate">
				<value value="//table[@bgcolor='#337fb2']/tbody/tr[position()&gt;1]/td[4]/text()" toType="list"/>
			</userAttribute>
		</baseBrowseTask>
		<totalPage value="1" toType="int"></totalPage>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/nasdaq-holding-institutional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="nasdaq-holding-institutional" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="false" dsm="nothing" taskName="nasdaq-holding-institutional" mbMemoryNeeded="1024">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<param name="quarter" type="int" value="0"/>
			<param name="year" type="int" value="0"/>
			<startUrl value="'http://www.nasdaq.com/symbol/' + stockid.toLowerCase() + '/institutional-holdings'" fromType="expression"/>
			<userAttribute name="id">
				<value value="stockid + '_' + endDate" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="6" toType="list" toEntryType="int"/>
			</userAttribute>
			<userAttribute name="DataType1">
				<value value="Text,Date" toType="list" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="data1">
				<value value="//div[@id='quotes_content_left_pnlInsider']/table[1]/tbody/tr/td" toType="externalList" toEntryType="string" optional="true"/>
			</userAttribute>
			<csvtransform outputType="byId" transformClass="org.cld.etl.csv.MultiRowTablesAsCSV">
			</csvtransform>
			<filter>function getDate(q) {
    if (q=='1') return '-03-31'
    if (q=='2') return '-06-30'
    if (q=='3') return '-09-30'
    if (q=='4') return '-12-31'
}
year==0 || quarter==0 || arr[1]&gt;=(year+getDate(quarter))</filter>
		</baseBrowseTask>
		<nextPage value="//ul[@id='pager']/ul[1]/li[last()-1]/a" optional="true"/>
		<lastPageCondition>
			<expression>nextPage == null</expression>
		</lastPageCondition>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/book/src/main/resources/baoliny.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" storeId="baoliny" rootVolume="999996" maxThread="2" productType="book">
	<CatTask isLeaf="false">
		<baseBrowseTask enableJS="false">
			<startUrl value="http://www.baoliny.com/"/>
			<idUrlMapping>
				<Token name="id" value="http://www.baoliny.com/"/>
			</idUrlMapping>
		</baseBrowseTask>
		<subItemList>
			<itemList value="//*[@id=&quot;wrapper&quot;]/div[4]/ul/li/a"/>
			<name value="./text()"/>
		</subItemList>
		<totalPageNum value="1"/>
	</CatTask>
	<CatTask isLeaf="true">
		<baseBrowseTask enableJS="false">
			<startUrl value="http://www.baoliny.com/sort_2_1.html"/>
			<idUrlMapping>
				<Token name="prefix" value="http://www.baoliny.com/sort_" type="string"/>
				<Token name="id" value="[0-9]+" type="regexp"/>
				<Token name="mid" value="_" type="string"/>
				<Token name="pageNum" value="[0-9]+" type="regexp"/>
				<Token name="suffix" value=".html" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
		<subItemList>
			<itemList value="//*[@id=&quot;newscontent&quot;]/div[1]/ul/li"/>
			<userAttribute name="author">
				<value value="./span[4]/text()"/>
			</userAttribute>
			<userAttribute name="utime">
				<value value="./span[5]/text()" toType="date" format="yy-MM-dd"/>
			</userAttribute>
			<name value="./span[2]/a/text()"/>
			<itemFullUrl value="./span[2]/a" toType="url"/>
		</subItemList>
		<totalPageNum value="//*[@id=&quot;pagelink&quot;]/a[last()]"/>
	</CatTask>
	<PrdTask>
		<baseBrowseTask enableJS="false">
			<startUrl value="http://www.baoliny.com/18/index.html"/>
			<userAttribute name="bookpageurls">
				<value value="//body/div/div[5]/div/div/div/ul/li/a | //body/div/div[5]/table/tbody/tr/td/a" toType="list"/>
			</userAttribute>
			<idUrlMapping>
				<Token name="prefix" value="http://www.baoliny.com/" type="string"/>
				<Token name="id" value="[0-9]+" type="regexp"/>
				<Token name="suffix" value="/index.html" type="string"/>
			</idUrlMapping>
		</baseBrowseTask>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/nasdaq-holding-top5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="nasdaq-holding-top5" productType="default">
	<PrdTask tryPattern="false">
		<baseBrowseTask enableJS="false" dsm="nothing" taskName="nasdaq-holding-top5" mbMemoryNeeded="1024">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate"/>
			<param name="endDate"/>
			<param name="HasHeader" type="boolean" value="false"/>
			<startUrl value="'http://www.nasdaq.com/symbol/' + stockid.toLowerCase() + '/ownership-summary'" fromType="expression"/>
			<userAttribute name="id">
				<value value="stockid + '_' + endDate" fromType="expression"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="2,2" toType="list" toEntryType="int"/>
			</userAttribute>
			<userAttribute name="RowCsvName">
				<value value="InstitutionalTop5,InsiderTop5" toType="list" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="DataType1">
				<value value="Text,Number" toType="list" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="DataType2">
				<value value="Text,Number" toType="list" toEntryType="string"/>
			</userAttribute>
			<userAttribute name="data1">
				<value value="//div[@id='topholders']/following-sibling::div[1]/div[1]/table/tbody/tr/td" toType="list" toEntryType="string" optional="true"/>
			</userAttribute>
			<userAttribute name="data2">
				<value value="//div[@id='topinsiders']/../following-sibling::div[1]/div[1]/table/tbody/tr/th[1]|//div[@id='topinsiders']/../following-sibling::div[1]/div[1]/table/tbody/tr/td" toType="list" toEntryType="string" optional="true"/>
			</userAttribute>
			<csvtransform outputType="byJobMulti" transformClass="org.cld.etl.csv.MultiRowTablesAsCSV">
			</csvtransform>
		</baseBrowseTask>
	</PrdTask>
</Tasks>

=== phillipcheng/ereminder/Reminder/modules/stock/src/main/resources/sina-stock-stock-structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mydoc\myprojects\ereminder\Reminder\modules\shopping\src\main\resources\Task_2_0.xsd" rootVolume="999990" storeId="sina-stock-stock-structure" productType="default">
	<PrdTask>
		<baseBrowseTask enableJS="true" taskName="stock-structure" dsm="hdfs">
			<param name="marketId"/>
			<param name="stockid"/>
			<param name="startDate" type="string"/>
			<param name="endDate" type="string"/>
			<startUrl value="http://vip.stock.finance.sina.com.cn/corp/go.php/vCI_StockStructure/stockid/[stockid].phtml"/>
			<userAttribute name="id">
				<value value="stockid" toType="string" fromScope="param"/>
			</userAttribute>
			<userAttribute name="ColNum">
				<value value="count(//table[@id='StockStructureNewTable0']/tbody/tr[1]/td)" toType="int"/>
			</userAttribute>
			<userAttribute name="ColDateIdx">
				<value value="0" toType="int"/> <!-- use 变动日期,  公告日期  maybe null -->
			</userAttribute>
			<userAttribute name="RowNum">
				<value value="count(//table[@id='StockStructureNewTable0']/tbody/tr)" toType="int"/>
			</userAttribute>
			<userAttribute name="data">
				<value value="//table[contains(@id,'StockStructureNewTable')]/tbody/tr/td" toType="list"/>
			</userAttribute>
			<csvtransform transformClass="org.cld.etl.csv.SpreadColTableAsCSV" outputType="byJobSingle"><!-- 1 file -->
				<outputDir value="raw/[startDate]_[endDate]/sina-stock-stock-structure/"/>
			</csvtransform>
		</baseBrowseTask>
	</PrdTask>
</Tasks>
